server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/db_identity"
    username: mysql
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "5qiuk4pnYdZoMr5KMTheVfRN8ZkF7vrWglQavuAYKZXH2iHaD2q3Kh0iIYkWq316"
  valid-duration: 10
  refreshable-duration: 120